cassandra {
  host = "cassandra.us-east-1.amazonaws.com"
  port = 9142
  ssl.enabled = true

  username = "amartya"
  password = "amartyapatil879"

  consistency = "LOCAL_QUORUM"

  truststore.path = "/Users/racit/cassandra_truststore.jks"
  truststore.password = "changeit"
}

s3 {
  bucket="ghatidataengineer"
  access_key = "abcdefghijklmnopqrstuvwxyz"
  secret_key = "abcdefghijklmnopqrstuvwxyz"
  endpoint = "s3.amazonaws.com"
  path.style.access = false
}

mysql {
    host_url = "jdbc:mysql://abcdefghijklmnopqrstuvwxyz"
    username = "admin"
    password = "Amartya123"
}

kafka {
  bootstrapServer = "localhost:9092"
  topic = "orders_avro_topic"
}
