# https://www.playframework.com/documentation/latest/Configuration
play.server.http.address = "0.0.0.0"
# Optional: Set the port if you want something other than the default (9000)
play.server.http.port = 9000
#play.http.filters = "filters.Filters"
#play.filters.enabled += "play.filters.cors.CORSFilter"


slick.dbs.default.profile="slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver="com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url="jdbc:mysql://amartya-abcdefghijklmnopqrstuvwxyz:3306/amartya_spark"
slick.dbs.default.db.user="admin"
slick.dbs.default.db.password="Amartya123"
play.evolutions.db.default.autoApply=true

# cassandra.contact-points = "cassandra.us-east-1.amazonaws.com"
# cassandra.port = 9142
# cassandra.auth.username = "Loyal+1-at-380276783862"
# cassandra.auth.password = "1nyE2gkY76Art6w4wAQMr1IucDM4NMmXODv48UP6PUINZRRxfjTuZWLJEjs="
# cassandra.ssl.enabled = true
# cassandra.ssl.truststore.path = "/Users/racit/cassandra_truststore.jks"
# cassandra.ssl.truststore.password = "changeit"
# cassandra.datacenter = "us-east-1"
cassandra {
  host = "cassandra.us-east-1.amazonaws.com"
  port = 9142
  ssl.enabled = true

  username = "abcdefghijklmnopqrstuvwxyz"
  password = "abcdefghijklmnopqrstuvwxyz"

  consistency = "LOCAL_QUORUM"

  truststore.path = "/Users/racit/cassandra_truststore.jks"
  truststore.password = "changeit"
  datacenter="us-east-1"

}

s3 {
  bucket="ghatidataengineer"
  access_key = "abcdefghijklmnopqrstuvwxyz"
  secret_key = "abcdefghijklmnopqrstuvwxyz"
  endpoint = "s3.amazonaws.com"
  region= "ap-southeast-2"
  path.style.access = false
}

